'use strict'

var trough = require('trough')
var config = require('./config')
var findPackage = require('./find-package')
var findExample = require('./find-example')
var generate = require('./generate')
var instrument = require('./instrument')
var run = require('./run')
var tokenize = require('./tokenize')
var write = require('./write')

module.exports = trough()
  .use(findPackage)
  .use(config)
  .use(findExample)
  .use(instrument)
  .use(write)
  .use(run)
  .use(tokenize)
  .use(generate)
